### ISSUE TITLE
User bios with many lines make the input field invisible

### ISSUE THREAD

**Issue by eunjibyte** [ProjectHoot/hoot-mobile#248] opened 2021-10-09 00:11 UTC
### Steps to reproduce
1.While logged in, tap the profile tab in the Play app.
2. Tap the pencil icon.
3. Tap the User bio field, type a character in, then tap return 42+ times. The input field should unexpectedly turn invisible.

**Comment by BrandonDyer64** [comment] 2021-10-09 02:20
The user edit form is currently unimplemented

**Comment by BrandonDyer64** [comment] 2021-10-09 02:51
Closing as duplicate of #197

**Closed by BrandonDyer64** 2021-10-09 02:51 UTC
